<?xml version="1.0" encoding="utf-8"?><workItemType dslVersion="3.0.0.0" Name="Task" source="C:\dev\graph-walker\Walker.Tests\TransitionDocument.xml" xmlns="http://schemas.microsoft.com/dsltools/WITDesigner" />